site_name: Technical Documentation
site_description: Technical Documentation
site_author: Anne-Laure CHARLES

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    extra_css:
      - stylesheets/extra.css
    extra:
      generator: false
      alternate:
        - name: English
          link: /en/
          lang: en
        - name: Deutsch
          link: /de/
          lang: de
      social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/squidfunk
          name: squidfunk on Twitter

nav:
    - 'Accueil': 'index.md'
    - 'Documentation': 'howWorking.md'
    - 'Languages':
        - 'Angular':
            - 'Introduction' : 'Angular/indexAngular.md'
        - 'PHP':
            - 'Introduction' : 'PHP/indexPHP.md'
        - 'TypeScript':
            - 'Introduction' : TypeScript/indexTypeScript.md
    - 'DevOps':
        - 'Docker': DevOps/indexDocker.md
        - 'Heroku': DevOps/indexHeroku.md
        - 'Dokku': DevOps/indexDokku.md
        - 'OpenShift': DevOps/indexOpenShift.md
    - 'Concepts/Architecure':
        - 'API':
            - 'API REST': indexAPIREST.md
    - 'Management': 'Management/management.md'
    - 'Stack':
        - 'Technical Stack': 'technicalStack.md'
        - 'Project Stack': 'projectStack.md'
    - 'Best Practices':
        - 'GIT': 'BestPractices/bestPracticesGit.md'
    - 'Others':
        - 'Guide Markdown': 'writing-your-docs.md'
        - 'GIT Portable': 'installation_git.md'
        - 'Questions': 'questions.md'
